### ISSUE TITLE
TypeScript imports / types not available

### ISSUE THREAD

**Issue by julrich1** [newrelic/newrelic-telemetry-sdk-node#27] opened 2020-06-05 17:04 UTC
## Description

The telemetry SDK provides some TypeScript exports but I don't see a clear way to import them properly. Are there plans to provide exports and types for TypeScript users?

## Steps to Reproduce

In order to import the MetricClient type, I have to do this:
`import { MetricClient } from '@newrelic/telemetry-sdk/dist/src/telemetry/metrics'`

## Expected Behavior

I would expect to do something like this to use the SDK in TypeScript:
`import { MetricClient } from '@newrelic/telemetry-sdk'`

**Comment by michaelgoin** [comment] 2020-06-05 17:14
HI @julrich1 ,

Currently, the `{MetricClient}` isn't exported directly at the index but through nested barrels. You can grab via `.telemetry.metrics`. There are a few examples in the readme you can leverage to help you.

So you'll likely do something like:

```js
const {
  MetricClient,
  GaugeMetric,
  MetricBatch,
} = require("@newrelic/telemetry-sdk").telemetry.metrics;
```

If you'd like to see the Metric and Span clients and the other constructs exported at the base-level, we can definitely consider. We were trying to keep some separation between Metrics, Spans and other mechanisms such as the supported logging interface. 

Thanks,

Michael

**Comment by julrich1** [comment] 2020-06-05 17:19
Thank you for the quick reply. When importing like this I cannot use the MetricClient as a type. 
I get this error - `'MetricClient' refers to a value, but is being used as a type here.ts(2749)`

**Comment by michaelgoin** [comment] 2020-06-05 17:21
Weird, we've def leveraged this and I recently know of one user using that exact snippet without issue.

Perhaps a TypeScript versioning/behavior issue.

Would you mind sharing your Node version, TypeScript version, `@newrelic/telemetry-sdk` version and maybe a code snippet of what you are trying?

Sorry for the troubles.

**Comment by julrich1** [comment] 2020-06-05 17:35
TypeScript v3.8.3
Node v12.14.1
NewRelic Telemetry SDK v0.2.0

Here is the simplest repro code snipped that shows the issue:
`const {
  MetricClient,
  GaugeMetric,
  MetricBatch,
} = require("@newrelic/telemetry-sdk").telemetry.metrics;

export default class MetricsProcessor {
  nrMetricClient: MetricClient

  constructor (nrMetricClient: MetricClient) {
    this.nrMetricClient = nrMetricClient
  }
}`

**Comment by michaelgoin** [comment] 2020-06-05 18:17
Thanks! I'm able to reproduce.

I'm guessing we missed testing as a type reference on a class. Not sure why the type exports/barrels are resulting in this behavior but hopefully can track down w/o too much churn. If anything jumps out to you that is wrong about our setup, don't hesitate to point it out or shoot a PR if you are feeling so inclined. :)

**Comment by michaelgoin** [comment] 2020-06-05 23:39
So it looks like TypeScript doesn't really like the exporting through layers of barrels. It kinda gives up on the type matching.

We'll prob rethinking how we are exporting things here. In the meantime, you *should* be able to use a fully resolved type like this:

```js
import { telemetry } from '@newrelic/telemetry-sdk'

export default class MetricsProcessor {
  nrMetricClient: telemetry.metrics.MetricClient

  constructor (nrMetricClient: telemetry.metrics.MetricClient) {
    this.nrMetricClient = nrMetricClient
  }
}
```

if you don't want to reach all the way into metrics via the path. Either way, not a great experience.

**Comment by julrich1** [comment] 2020-06-08 16:28
Thanks @michaelgoin, this is a sufficient work-around for now.

**Comment by astormnewrelic** [comment] 2020-06-09 23:47
Glad to hear a workaround's in place @julrich1 -- we'll be leaving this issue open as a our placeholder "be better about our exports"

**Comment by michaelgoin** [comment] 2021-09-03 16:12
We have deprecated this module/repository and plan to EOL likely in the next few months. Closing out all issues.

**Closed by michaelgoin** 2021-09-03 16:12 UTC
Labels: bug
